# Generated by Django 6.1.1 on 2026-10-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcode',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
